version: '3'

services:
  g4f-slim:
    container_name: g4f-slim
    image: hlohaus789/g4f:latest-slim
    build:
      context: .
      dockerfile: docker/Dockerfile-slim
    command: python -m g4f --debug --port 8082
    volumes:
      - .:/app
    ports:
      - '8082:8082'
      - '1337:8082'
